# Generated by Django 4.2.9 on 2025-11-07 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de técnico')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('ordenes_completadas', models.IntegerField(default=0, verbose_name='Órdenes completadas')),
                ('ordenes_pendientes', models.IntegerField(default=0, verbose_name='Órdenes pendientes')),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Cumplimiento')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Calificación promedio')),
                ('activo', models.BooleanField(default=True, verbose_name='Técnico activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['-porcentaje_cumplimiento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=100, unique=True, verbose_name='Número de orden')),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(verbose_name='Fecha de asignación')),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ejecución')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='tecnicos.tecnico', verbose_name='Técnico asignado')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='InformeMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(verbose_name='Comentarios y observaciones')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='informes/pdfs/%Y/%m/', verbose_name='Archivo PDF')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('fecha_envio_email', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.CharField(default='Sistema', max_length=100, verbose_name='Creado por')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='tecnicos.ordentrabajo', verbose_name='Orden de trabajo')),
            ],
            options={
                'verbose_name': 'Informe de Mejora',
                'verbose_name_plural': 'Informes de Mejora',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='informes/imagenes/%Y/%m/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción de la imagen')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tecnicos.informemejora', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Imagen de Informe',
                'verbose_name_plural': 'Imágenes de Informes',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
    ]
