# Generated by Django 4.2.9 on 2025-11-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='agencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Agencia'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona'),
        ),
    ]
