# Generated by Django 4.2.9 on 2025-11-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0002_ordentrabajo_agencia_ordentrabajo_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='infancia',
            field=models.IntegerField(default=0, verbose_name='Infancia'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='porcentaje_infancia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Infancia'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='total_infancias',
            field=models.IntegerField(default=0, verbose_name='Total infancias'),
        ),
    ]
