# Generated by Django 4.2.9 on 2026-05-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_ordentrabajo_infancia_tecnico_porcentaje_infancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informemejora',
            name='latitud_gps',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud GPS'),
        ),
        migrations.AddField(
            model_name='informemejora',
            name='longitud_gps',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud GPS'),
        ),
    ]
