# Generated by Django 4.2.9 on 2026-05-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0004_add_gps_to_informemejora'),
    ]

    operations = [
        migrations.AddField(
            model_name='informemejora',
            name='email_inspector',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del inspector'),
        ),
    ]
