# Generated by Django 4.2.9 on 2026-05-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0005_add_email_inspector_to_informemejora'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularizacionInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario de regularización')),
                ('creado_por', models.CharField(max_length=100, verbose_name='Creado por')),
                ('email_inspector', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email inspector')),
                ('latitud_gps', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud_gps', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de regularización')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='regularizaciones/pdfs/%Y/%m/')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularizaciones', to='tecnicos.informemejora', verbose_name='Informe original')),
            ],
            options={
                'verbose_name': 'Regularización de Informe',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoRegularizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='regularizaciones/fotos/%Y/%m/')),
                ('orden', models.IntegerField(default=0)),
                ('regularizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tecnicos.regularizacioninforme')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
